options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/buildpacks/builder
    entrypoint: pack
    args:
      - build
      - gcr.io/$PROJECT_ID/advanced:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder
      - --path
      - .

images:
  - gcr.io/$PROJECT_ID/advanced:$COMMIT_SHA
