options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/buildpacks/builder
    entrypoint: pack
    args:
      - build
      - gcr.io/$PROJECT_ID/advanced:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder
      - --path
      - .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - bleedbuddy
      - --image=gcr.io/$PROJECT_ID/advanced:$COMMIT_SHA
      - --region=us-west2
      - --platform=managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/advanced:$COMMIT_SHA
